/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import javax.swing.UIManager;
import java.beans.PropertyVetoException;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.commons.logging.Log;


/**
 *
 * @author ASUS
 */
public class frmPrincipal extends javax.swing.JFrame {
    
    public static int idtrabajador;
    

    /**
     * Creates new form NewMDIApplication
     */
    public frmPrincipal() {
        initComponents();

        

        
    }

    /**
     * This method is called from within th1e constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rSLabelHora1 = new rojeru_san.RSLabelHora();
        rSLabelFecha1 = new rojeru_san.RSLabelFecha();
        jLabel1 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuSysVentas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        menuAlmacen = new javax.swing.JMenu();
        menuArticulo = new javax.swing.JMenuItem();
        menuCompras = new javax.swing.JMenu();
        menuIngresarMercaderia = new javax.swing.JMenuItem();
        menuVentas = new javax.swing.JMenu();
        menuRegistrarVentas = new javax.swing.JMenuItem();
        menuMantenimiento = new javax.swing.JMenu();
        menuTrabajador = new javax.swing.JMenuItem();
        menuProveedor = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(0, 204, 153));
        desktopPane.setAutoscrolls(true);
        desktopPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        desktopPane.setDoubleBuffered(true);
        desktopPane.setFocusTraversalPolicyProvider(true);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Hora:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Fecha:");

        rSLabelHora1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rSLabelHora1.setForeground(new java.awt.Color(0, 0, 0));

        rSLabelFecha1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rSLabelFecha1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Usuario:");

        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblusuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblusuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSLabelFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel4, jLabel5});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblusuario, rSLabelFecha1, rSLabelHora1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSLabelFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblusuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel4, jLabel5});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblusuario, rSLabelFecha1, rSLabelHora1});

        desktopPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1402, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 538, Short.MAX_VALUE))
        );

        menuSysVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/acceso.png"))); // NOI18N
        menuSysVentas.setMnemonic('f');
        menuSysVentas.setText("SysVentas");

        jMenuItem1.setText("Iniciar Seccion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuSysVentas.add(jMenuItem1);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        menuSysVentas.add(exitMenuItem);

        menuBar.add(menuSysVentas);

        menuAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar.png"))); // NOI18N
        menuAlmacen.setMnemonic('e');
        menuAlmacen.setText("Almacen");

        menuArticulo.setMnemonic('y');
        menuArticulo.setText("Producto");
        menuArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArticuloActionPerformed(evt);
            }
        });
        menuAlmacen.add(menuArticulo);

        menuBar.add(menuAlmacen);

        menuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/PrecioProd.png"))); // NOI18N
        menuCompras.setMnemonic('h');
        menuCompras.setText("Compras");

        menuIngresarMercaderia.setMnemonic('c');
        menuIngresarMercaderia.setText("Registrar Compras");
        menuIngresarMercaderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarMercaderiaActionPerformed(evt);
            }
        });
        menuCompras.add(menuIngresarMercaderia);

        menuBar.add(menuCompras);

        menuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/NombreProducto.png"))); // NOI18N
        menuVentas.setText("Ventas");

        menuRegistrarVentas.setText("Registrar Ventas");
        menuRegistrarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarVentasActionPerformed(evt);
            }
        });
        menuVentas.add(menuRegistrarVentas);

        menuBar.add(menuVentas);

        menuMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/DescProd.png"))); // NOI18N
        menuMantenimiento.setText("Mantenimiento");

        menuTrabajador.setText(" Trabajador");
        menuTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTrabajadorActionPerformed(evt);
            }
        });
        menuMantenimiento.add(menuTrabajador);

        menuProveedor.setMnemonic('a');
        menuProveedor.setText("Proveedor");
        menuProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProveedorActionPerformed(evt);
            }
        });
        menuMantenimiento.add(menuProveedor);

        menuCliente.setText(" Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        menuMantenimiento.add(menuCliente);

        menuBar.add(menuMantenimiento);

        menuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/StockProd.png"))); // NOI18N
        menuConsultas.setText("Consultas");

        jMenu1.setText("REPORTE DE VENTAS");

        jMenuItem5.setText("CLIENTE");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("TRABAJADOR");
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("OTROS");
        jMenu1.add(jMenuItem7);

        menuConsultas.add(jMenu1);

        jMenuItem3.setText("REPORTE DE PRODUCTOS VENDIDOS");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuConsultas.add(jMenuItem3);

        jMenuItem4.setText("REPORTE STOCK PRODUCTOS");
        menuConsultas.add(jMenuItem4);

        menuBar.add(menuConsultas);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/usuarioA.png"))); // NOI18N
        jMenu5.setText("Ayuda");
        menuBar.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/login.png"))); // NOI18N
        jMenu6.setText("Salir");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        menuBar.add(jMenu6);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktopPane)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        desktopPane.getAccessibleContext().setAccessibleDescription("");
        desktopPane.getAccessibleContext().setAccessibleParent(desktopPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProveedorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuProveedorActionPerformed

    private void menuArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArticuloActionPerformed
        // TODO add your handling code here:        
//        frmArticulo2 form=new frmArticulo2();
//        desktopPane.add(form);
//        form.toFront();
//        form.setVisible(true);
    }//GEN-LAST:event_menuArticuloActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuTrabajadorActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void menuIngresarMercaderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarMercaderiaActionPerformed
        // TODO add your handling code here:
        //controlventanas.abrir(frmCompra11.getInstancia());
    }//GEN-LAST:event_menuIngresarMercaderiaActionPerformed

    private void menuRegistrarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarVentasActionPerformed
        // TODO add your handling code here:
//        frmComprobante form=new frmComprobante();
//        desktopPane.add(form);
//        form.toFront();
//        form.setVisible(true);
//        try {
//            form.setMaximum(false);
//        } catch (PropertyVetoException ex) {
//            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE,null,ex);   
//        }
    }//GEN-LAST:event_menuRegistrarVentasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("System".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblusuario;
    private javax.swing.JMenu menuAlmacen;
    private javax.swing.JMenuItem menuArticulo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenu menuCompras;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuItem menuIngresarMercaderia;
    public javax.swing.JMenu menuMantenimiento;
    private javax.swing.JMenuItem menuProveedor;
    private javax.swing.JMenuItem menuRegistrarVentas;
    private javax.swing.JMenu menuSysVentas;
    private javax.swing.JMenuItem menuTrabajador;
    public javax.swing.JMenu menuVentas;
    private rojeru_san.RSLabelFecha rSLabelFecha1;
    private rojeru_san.RSLabelHora rSLabelHora1;
    // End of variables declaration//GEN-END:variables

}
