/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author Elizabeth
 */
public class frmReporteProducto extends javax.swing.JFrame {
        Color boton_f=new Color(41,86,154);
        Color boton_b=new Color(0,204,153);
        Color encabezado=new Color(0,204,153);
        Color fondos=new Color(255,255,255);
        Color borde=new Color(0,204,153);


    /**
     * Creates new form frmReporteProducto
     */
    public frmReporteProducto() {
        initComponents();
        jpFondo1.setBackground(encabezado);
        jpFondo2.setBackground(fondos);
        jpFondo3.setBackground(fondos);
        jpFondo4.setBackground(fondos);
        jpFondo4.setBorder(BorderFactory.createLineBorder(encabezado, 3));
        jpFondo5.setBorder(BorderFactory.createLineBorder(encabezado, 3));
        
        
        ImageIcon icono_buscar=new ImageIcon(getClass().getResource("/Iconos/buscar.png"));
        btnBuscar.setBackground(boton_b);
        btnBuscar.setIcon(icono_buscar);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondo5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaListadoTienda = new javax.swing.JTable();
        jpFondo2 = new javax.swing.JPanel();
        rbCodigo = new javax.swing.JRadioButton();
        rbNomTienda = new javax.swing.JRadioButton();
        rbNomTienda1 = new javax.swing.JRadioButton();
        btnReportes = new javax.swing.JButton();
        jpFondo4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        dcBuscarDel = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        dcBuscarAl = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();
        jpFondo3 = new javax.swing.JPanel();
        rbNomTienda3 = new javax.swing.JRadioButton();
        rbNomTienda4 = new javax.swing.JRadioButton();
        jpFondo1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpFondo5.setBackground(new java.awt.Color(255, 255, 255));
        jpFondo5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpFondo5.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Buscar:");

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        TablaListadoTienda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "CATEGORIA", "NOMBRE DEL PRODUCTO"
                ,"CANTIDAD"
            }
        ));
        TablaListadoTienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaListadoTiendaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaListadoTiendaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TablaListadoTienda);

        rbCodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbCodigo.setForeground(new java.awt.Color(0, 0, 102));
        rbCodigo.setText("Codigo");
        rbCodigo.setFocusable(false);
        rbCodigo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rbCodigo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rbCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCodigoActionPerformed(evt);
            }
        });

        rbNomTienda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbNomTienda.setForeground(new java.awt.Color(0, 0, 102));
        rbNomTienda.setText("Nombre Producto");
        rbNomTienda.setFocusable(false);
        rbNomTienda.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rbNomTienda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rbNomTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNomTiendaActionPerformed(evt);
            }
        });

        rbNomTienda1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbNomTienda1.setForeground(new java.awt.Color(0, 0, 102));
        rbNomTienda1.setText("Categoria");
        rbNomTienda1.setFocusable(false);
        rbNomTienda1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rbNomTienda1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rbNomTienda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNomTienda1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFondo2Layout = new javax.swing.GroupLayout(jpFondo2);
        jpFondo2.setLayout(jpFondo2Layout);
        jpFondo2Layout.setHorizontalGroup(
            jpFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondo2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(rbCodigo)
                .addGap(18, 18, 18)
                .addComponent(rbNomTienda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbNomTienda1)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jpFondo2Layout.setVerticalGroup(
            jpFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbNomTienda1)
                    .addGroup(jpFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbNomTienda)
                        .addComponent(rbCodigo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnReportes.setBackground(new java.awt.Color(0, 0, 51));
        btnReportes.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(102, 153, 255));
        btnReportes.setText("Imprimir");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Del:");

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("al");

        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFondo4Layout = new javax.swing.GroupLayout(jpFondo4);
        jpFondo4.setLayout(jpFondo4Layout);
        jpFondo4Layout.setHorizontalGroup(
            jpFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondo4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcBuscarDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcBuscarAl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jpFondo4Layout.setVerticalGroup(
            jpFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondo4Layout.createSequentialGroup()
                .addGroup(jpFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcBuscarAl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpFondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpFondo4Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(dcBuscarDel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpFondo4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpFondo4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBuscar, dcBuscarAl, dcBuscarDel, jLabel17, jLabel8});

        jpFondo3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordenar por", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 51))); // NOI18N
        jpFondo3.setForeground(new java.awt.Color(153, 204, 255));

        rbNomTienda3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbNomTienda3.setForeground(new java.awt.Color(0, 0, 102));
        rbNomTienda3.setText("Nombre Producto");
        rbNomTienda3.setFocusable(false);
        rbNomTienda3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rbNomTienda3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rbNomTienda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNomTienda3ActionPerformed(evt);
            }
        });

        rbNomTienda4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbNomTienda4.setForeground(new java.awt.Color(0, 0, 102));
        rbNomTienda4.setText("Cantidad");
        rbNomTienda4.setFocusable(false);
        rbNomTienda4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rbNomTienda4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rbNomTienda4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNomTienda4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFondo3Layout = new javax.swing.GroupLayout(jpFondo3);
        jpFondo3.setLayout(jpFondo3Layout);
        jpFondo3Layout.setHorizontalGroup(
            jpFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondo3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(rbNomTienda3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbNomTienda4)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jpFondo3Layout.setVerticalGroup(
            jpFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondo3Layout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addGroup(jpFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbNomTienda4)
                    .addComponent(rbNomTienda3)))
        );

        javax.swing.GroupLayout jpFondo5Layout = new javax.swing.GroupLayout(jpFondo5);
        jpFondo5.setLayout(jpFondo5Layout);
        jpFondo5Layout.setHorizontalGroup(
            jpFondo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondo5Layout.createSequentialGroup()
                .addComponent(jpFondo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpFondo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondo5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFondo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpFondo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpFondo5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReportes)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpFondo5Layout.setVerticalGroup(
            jpFondo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondo5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpFondo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpFondo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(9, 9, 9)
                .addGroup(jpFondo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpFondo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpFondo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpFondo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpFondo1.setBackground(new java.awt.Color(0, 204, 153));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Reporte de Productos Vendidos");

        javax.swing.GroupLayout jpFondo1Layout = new javax.swing.GroupLayout(jpFondo1);
        jpFondo1.setLayout(jpFondo1Layout);
        jpFondo1Layout.setHorizontalGroup(
            jpFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpFondo1Layout.setVerticalGroup(
            jpFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpFondo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpFondo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpFondo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtbuscarKeyReleased

    private void TablaListadoTiendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaListadoTiendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaListadoTiendaMouseClicked

    private void TablaListadoTiendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaListadoTiendaMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_TablaListadoTiendaMousePressed

    private void rbCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCodigoActionPerformed
        // TODO add your handling code here:
        txtbuscar.setText("");
        txtbuscar.setEnabled(true);
    }//GEN-LAST:event_rbCodigoActionPerformed

    private void rbNomTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomTiendaActionPerformed
        // TODO add your handling code here:
        txtbuscar.setText("");
        txtbuscar.setEnabled(true);
    }//GEN-LAST:event_rbNomTiendaActionPerformed

    private void rbNomTienda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomTienda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNomTienda1ActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        

        //listarXfechas(fecha_ini, fecha_fin);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void rbNomTienda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomTienda3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNomTienda3ActionPerformed

    private void rbNomTienda4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomTienda4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNomTienda4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReporteProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TablaListadoTienda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnReportes;
    private com.toedter.calendar.JDateChooser dcBuscarAl;
    private com.toedter.calendar.JDateChooser dcBuscarDel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpFondo1;
    private javax.swing.JPanel jpFondo2;
    private javax.swing.JPanel jpFondo3;
    private javax.swing.JPanel jpFondo4;
    private javax.swing.JPanel jpFondo5;
    private javax.swing.JRadioButton rbCodigo;
    private javax.swing.JRadioButton rbNomTienda;
    private javax.swing.JRadioButton rbNomTienda1;
    private javax.swing.JRadioButton rbNomTienda3;
    private javax.swing.JRadioButton rbNomTienda4;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
